version: "3"

services:
    database:
        image: postgres
        container_name: postgres_db
        restart: always
        ports:
            - 2000:5432
        env_file:
            - ./back-end/.env
        volumes:
            - postgres:/var/lib/postgresql/data

    server:
        container_name: node_server
        build:
            context: ./back-end
            dockerfile: Dockerfile
        ports:
            - 5000:5000
        depends_on:
            - database
        env_file:
            - ./back-end/.env

    react:
        container_name: react_app
        build:
            context: ./front-end
            dockerfile: Dockerfile
        volumes:
            - build:/var/www/html

    nginx:
        container_name: nginx_server
        build: 
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - 80:80
        volumes:
            - build:/var/www/html
        depends_on:
            - database
            - server
            - react

volumes:
    postgres:
    build:
